services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx:test
    container_name: nginx
    ports:
      - "9090:9090"
      - "9091:9091"
      - "9092:9092"
      - "9093:9093"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
