name: 42Cursus CPP Makefile Test

on:
  pull_request:
    types: [opened, reopened]

jobs:
  test-makefiles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: 42Cursus C/CPP Makefile Testing
        uses: fing9/42Cursus-Makefile-Test@v3.0.2
